/* LOANS */
export const GET_LOANS = 'GET_LOANS';
export const GET_LOANS_SUCCESS = 'GET_LOANS_SUCCESS';
export const GET_LOANS_FAILURE = 'GET_LOANS_FAILURE';

export const GET_60_DAY_LOANS = 'GET_60_DAY_LOANS';
export const GET_60_DAY_LOANS_SUCCESS = 'GET_60_DAY_LOANS_SUCCESS';
export const GET_60_DAY_LOANS_FAILURE = 'GET_60_DAY_LOANS_FAILURE';


/* LOAN */
export const GET_LOAN = 'GET_LOAN';
export const GET_LOAN_SUCCESS = 'GET_LOAN_SUCCESS';
export const GET_LOAN_FAILURE = 'GET_LOAN_FAILURE';

export const CREATE_LOAN = 'CREATE_LOAN';
export const CREATE_LOAN_SUCCESS = 'CREATE_LOAN_SUCCESS';
export const CREATE_LOAN_FAILURE = 'CREATE_LOAN_FAILURE';

export const EDIT_LOAN = 'EDIT_LOAN';
export const EDIT_LOAN_SUCCESS = 'EDIT_LOAN_SUCCESS';
export const EDIT_LOAN_FAILURE = 'EDIT_LOAN_FAILURE';

export const DELETE_LOAN = 'DELETE_LOAN';
export const DELETE_LOAN_SUCCESS = 'DELETE_LOAN_SUCCESS';
export const DELETE_LOAN_FAILURE = 'DELETE_LOAN_FAILURE';

export const CLEAR_LOAN = 'CLEAR_LOAN';