[context.production]
    environment = { REACT_APP_REACT_APP_KDM_API_ENDPOINT = "http://50f1ee0b-d41c9b4-18945ff170ff64b9.elb.us-west-2.amazonaws.com:8080/api/v1", CI = "false" }

[context.deploy-preview]
    environment = { REACT_APP_REACT_APP_KDM_API_ENDPOINT = "http://50f1ee0b-d41c9b4-18945ff170ff64b9.elb.us-west-2.amazonaws.com:8080/api/v1", CI = "false" }
