export const GET_SPONSOR = 'GET_SPONSOR';
export const GET_SPONSOR_SUCCESS = 'GET_SPONSOR_SUCCESS';
export const GET_SPONSOR_FAILURE = 'GET_SPONSOR_FAILURE';

export const CREATE_SPONSOR = 'CREATE_SPONSOR';
export const CREATE_SPONSOR_SUCCESS = 'CREATE_SPONSOR_SUCCESS';
export const CREATE_SPONSOR_FAILURE = 'CREATE_SPONSOR_FAILURE';

export const EDIT_SPONSOR = 'EDIT_SPONSOR';
export const EDIT_SPONSOR_SUCCESS = 'EDIT_SPONSOR_SUCCESS';
export const EDIT_SPONSOR_FAILURE = 'EDIT_SPONSOR_FAILURE';

export const DELETE_SPONSOR = 'DELETE_SPONSOR';
export const DELETE_SPONSOR_SUCCESS = 'DELETE_SPONSOR_SUCCESS';
export const DELETE_SPONSOR_FAILURE = 'DELETE_SPONSOR_FAILURE';

export const CLEAR_SPONSOR = 'CLEAR_SPONSOR';