/* SECURITIES */
export const GET_SECURITIES = 'GET_SECURITIES';
export const GET_SECURITIES_SUCCESS = 'GET_SECURITIES_SUCCESS';
export const GET_SECURITIES_FAILURE = 'GET_SECURITIES_FAILURE';

// export const GET_60_DAY_SECURITIES = 'GET_60_DAY_SECURITIES';
// export const GET_60_DAY_SECURITIES_SUCCESS = 'GET_60_DAY_SECURITIES_SUCCESS';
// export const GET_60_DAY_SECURITIES_FAILURE = 'GET_60_DAY_SECURITIES_FAILURE';


/* SECURITY */
export const GET_SECURITY = 'GET_SECURITY';
export const GET_SECURITY_SUCCESS = 'GET_SECURITY_SUCCESS';
export const GET_SECURITY_FAILURE = 'GET_SECURITY_FAILURE';

export const CREATE_SECURITY = 'CREATE_SECURITY';
export const CREATE_SECURITY_SUCCESS = 'CREATE_SECURITY_SUCCESS';
export const CREATE_SECURITY_FAILURE = 'CREATE_SECURITY_FAILURE';

export const EDIT_SECURITY = 'EDIT_SECURITY';
export const EDIT_SECURITY_SUCCESS = 'EDIT_SECURITY_SUCCESS';
export const EDIT_SECURITY_FAILURE = 'EDIT_SECURITY_FAILURE';

export const DELETE_SECURITY = 'DELETE_SECURITY';
export const DELETE_SECURITY_SUCCESS = 'DELETE_SECURITY_SUCCESS';
export const DELETE_SECURITY_FAILURE = 'DELETE_SECURITY_FAILURE';

export const CLEAR_SECURITY = 'CLEAR_SECURITY';

export const EDIT_SECURITY_RATINGS = 'EDIT_SECURITY_RATINGS';
export const EDIT_SECURITY_RATINGS_SUCCESS = 'EDIT_SECURITY_RATINGS_SUCCESS';
export const EDIT_SECURITY_RATINGS_FAILURE = 'EDIT_SECURITY_RATINGS_FAILURE';

export const GET_SECURITY_LOANS = 'GET_SECURITY_LOANS';
export const GET_SECURITY_LOANS_SUCCESS = 'GET_SECURITY_LOANS_SUCCESS';
export const GET_SECURITY_LOANS_FAILURE = 'GET_SECURITY_LOANS_FAILURE';