# docker-compose.yml
version: '3'
services:
  webapp:
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/kdm
      - spring.datasource.username=dbusername
      - spring.datasource.password=dbpassword
      - spring.flyway.enabled=true
      - spring.profiles.active=no_kdm_security
      - tmo.api.token=FD1F722B2C3F48409050D9A52E5B2DDA
    build:
        context: ./
        dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - kdm-database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
volumes:
  kdm-database-data:
    external: true