export const GET_PROPERTY = 'GET_PROPERTY';
export const GET_PROPERTY_SUCCESS = 'GET_PROPERTY_SUCCESS';
export const GET_PROPERTY_FAILURE = 'GET_PROPERTY_FAILURE';

export const CREATE_PROPERTY = 'CREATE_PROPERTY';
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS';
export const CREATE_PROPERTY_FAILURE = 'CREATE_PROPERTY_FAILURE';

export const EDIT_PROPERTY = 'EDIT_PROPERTY';
export const EDIT_PROPERTY_SUCCESS = 'EDIT_PROPERTY_SUCCESS';
export const EDIT_PROPERTY_FAILURE = 'EDIT_PROPERTY_FAILURE';

export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS';
export const DELETE_PROPERTY_FAILURE = 'DELETE_PROPERTY_FAILURE';

export const ASSIGN_APPRAISAL = 'ASSIGN_APPRAISAL';
export const ASSIGN_APPRAISAL_SUCCESS = 'ASSIGN_APPRAISAL_SUCCESS';
export const ASSIGN_APPRAISAL_FAILURE = 'ASSIGN_APPRAISAL_FAILURE';

export const CLEAR_PROPERTY = 'CLEAR_PROPERTY';