export const GET_RATINGS = 'GET_RATINGS';
export const GET_RATINGS_SUCCESS = 'GET_RATINGS_SUCCESS';
export const GET_RATINGS_FAILURE = 'GET_RATINGS_FAILURE';

export const GET_RATING = 'GET_RATING';
export const GET_RATING_SUCCESS = 'GET_RATING_SUCCESS';
export const GET_RATING_FAILURE = 'GET_RATING_FAILURE';

export const CREATE_RATING = 'CREATE_RATING';
export const CREATE_RATING_SUCCESS = 'CREATE_RATING_SUCCESS';
export const CREATE_RATING_FAILURE = 'CREATE_RATING_FAILURE';

export const EDIT_RATING = 'EDIT_RATING';
export const EDIT_RATING_SUCCESS = 'EDIT_RATING_SUCCESS';
export const EDIT_RATING_FAILURE = 'EDIT_RATING_FAILURE';

export const DELETE_RATING = 'DELETE_RATING';
export const DELETE_RATING_SUCCESS = 'DELETE_RATING_SUCCESS';
export const DELETE_RATING_FAILURE = 'DELETE_RATING_FAILURE';

export const CLEAR_RATING = 'CLEAR_RATING';