export const GET_BORROWERS = 'GET_BORROWERS';
export const GET_BORROWERS_SUCCESS = 'GET_BORROWERS_SUCCESS';
export const GET_BORROWERS_FAILURE = 'GET_BORROWERS_FAILURE';

export const GET_BORROWER = 'GET_BORROWER';
export const GET_BORROWER_SUCCESS = 'GET_BORROWER_SUCCESS';
export const GET_BORROWER_FAILURE = 'GET_BORROWER_FAILURE';

export const CREATE_BORROWER = 'CREATE_BORROWER';
export const CREATE_BORROWER_SUCCESS = 'CREATE_BORROWER_SUCCESS';
export const CREATE_BORROWER_FAILURE = 'CREATE_BORROWER_FAILURE';

export const EDIT_BORROWER = 'EDIT_BORROWER';
export const EDIT_BORROWER_SUCCESS = 'EDIT_BORROWER_SUCCESS';
export const EDIT_BORROWER_FAILURE = 'EDIT_BORROWER_FAILURE';

export const DELETE_BORROWER = 'DELETE_BORROWER';
export const DELETE_BORROWER_SUCCESS = 'DELETE_BORROWER_SUCCESS';
export const DELETE_BORROWER_FAILURE = 'DELETE_BORROWER_FAILURE';

export const CLEAR_BORROWER = 'CLEAR_BORROWER';