## Spring boot and dependencies properties - start here
auth0:
  audience: http://localhost:8080/api/
server:
  error:
    include-message: always
spring:
  application:
    name: kdm-api
# The following spring.datasource values should be send from command line
#  datasource:  
#    url: jdbc:postgresql://somehost:someport/somedatabase
#    username: someuser
#    password: somepassword
  flyway:
    enabled: false
    ignoreMissingMigrations: true
    outOfOrder: true
    table: FLYWAY_SCHEMA_HISTORY    
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        temp: 
          use_jdbc_metadata_defaults: false
    show-sql: true
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: DETECT
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-2wiawl6z.us.auth0.com/
logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-70.70logger{69}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%xEx}}
  level:
    com.kdm.web.controller.RestResponseEntityExceptionHandler: TRACE
#    root: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

## KDM properties - start here
kdm:
  api:
    allowedOrigins: http://localhost:8080,http://localhost:3000
tmo:
  api:
    url: https://absws.com
# The following value should be send from command line or environment variable
    token:
    database: Korth Direct Mortgage Servicing