## Spring boot and dependencies properties - start here
server:
  error:
    include-message: always
spring:
  application:
    name: kdm-api
# The following spring.datasource values should be send from command line
#  datasource:  
#    url: jdbc:postgresql://somehost:someport/somedatabase
#    username: someuser
#    password: somepassword
  flyway:
    enabled: false
    ignoreMissingMigrations: true
    outOfOrder: true
    table: FLYWAY_SCHEMA_HISTORY
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
#        format_sql: true
        temp: 
          use_jdbc_metadata_defaults: false
#    show-sql: true
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: DETECT
logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-70.70logger{69}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%xEx}}
#  level:
#    root: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

## KDM properties - start here
kdm:
  api:
    allowedOrigins: http://localhost:8080
